# Generated by Django 4.0.4 on 2022-06-07 03:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models3d',
            name='content',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
